# -*- coding: utf-8 -*-
"""predict function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11SKw-PGeAvEVo3IhuZAEVnO9PiQGEnVn
"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# CAT_COLS = ['format', 'city', 'contract','experience','education','employment', 'emp_brand','courses', 'test_task'] #,'test_task'
# model = CatBoostRegressor(iterations=3000,
#                           early_stopping_rounds=100,
#                           grow_policy = 'Depthwise',
#                           depth=8,
#                           loss_function="MAE",
#                           cat_features= CAT_COLS,
#                           random_state=12345,
#                           l2_leaf_reg = 1,
#                           learning_rate=0.03,
#                           verbose=10)
# 
# # model = CatBoostRegressor(loss_function="RMSE", iterations=150)
# 
# # model.fit(features_train_cat, target_train_cat, cat_features=cat_features)
# 
# #print('время обучения модели')

# Commented out IPython magic to ensure Python compatibility.
# %%time
# pred_valid = model.predict(features_valid_cat)
# print('время предсказания')
# result_cat2 = mean_absolute_error(target_valid_cat, pred_valid)
# print("MAE cat на валидационной выборке:", result_cat2)