# -*- coding: utf-8 -*-
"""preprocessing function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12AMY9uXHpq9cqgrdOfsJ1j8ksppBUsmt

Cписок признаков на входе в датасет

*   emp_brand
*   courses
*   city
*   contract
*   format
*   experience
*   education
*   test task
*   employment


*   +1024 embedding from BERT
"""

def tags_clean(x, nan_value= None):
    for column in x:
        txt = re.sub(r'(https?://[\S]+)', 'есть', x) # html tags change to spaces
        #txt = re.sub(COMMENTS, ' ', txt) # comments in parentheses change to spaces
        # txt = ' '.join(txt.split())
    return txt

data_good_cat['test_task']= data_good_cat['test_task'].fillna('нет')
#датасет и так невелик, поэтому нашла выход чем нейтральным заполнить пропуски

data_good_cat['test_task'] = data_good_cat['test_task'].apply(tags_clean)

data_cat = pd.concat([data_good_cat, df_features], axis=1)
#добавление эмбеддингов





